/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WZMKK90MfGA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WZMKK90MfGA= >>
// ----------- >>
public class Cliente {
    // ----------- << attribute.annotations@AAAAAAF9WZtIU95V284= >>
    // ----------- >>
    private int idCliente;

    // ----------- << attribute.annotations@AAAAAAF9WZvXFN5dbsw= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAF9WZwggN5ku6U= >>
    // ----------- >>
    private int edad;

    // ----------- << attribute.annotations@AAAAAAF9WZxNh95r3u8= >>
    // ----------- >>
    private String correo;

    // ----------- << attribute.annotations@AAAAAAF9WZ/sUN5yegw= >>
    // ----------- >>
    private String direccion;

    // ----------- << attribute.annotations@AAAAAAF9beSYYlB2rNo= >>
    // ----------- >>
    private Transaccion ;

    // ----------- << attribute.annotations@AAAAAAF9beUgClK6a8g= >>
    // ----------- >>
    private ManejadorBD ;

    // ----------- << attribute.annotations@AAAAAAF9bebI4FlMmMU= >>
    // ----------- >>
    private ManejadorBD ;

    private int getIdCliente() {
        return idCliente;
    }

    private String getNombre() {
        return nombre;
    }

    private int getEdad() {
        return edad;
    }

    private String getCorreo() {
        return correo;
    }

    private String getDireccion() {
        return direccion;
    }

    public Transaccion get() {
        return ;
    }

    public ManejadorBD get() {
        return ;
    }

    public ManejadorBD get() {
        return ;
    }

    private void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    private void setNombre(String nombre) {
        this.nombre = nombre;
    }

    private void setEdad(int edad) {
        this.edad = edad;
    }

    private void setCorreo(String correo) {
        this.correo = correo;
    }

    private void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public void set(Transaccion ) {
        this. = ;
    }

    public void set(ManejadorBD ) {
        this. = ;
    }

    public void set(ManejadorBD ) {
        this. = ;
    }

    public void link(Transaccion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(ManejadorBD _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(ManejadorBD _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF9WbKVrd9KZF8= >>
    // ----------- >>
    public void registrar() {
    // ----------- << method.body@AAAAAAF9WbKVrd9KZF8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbLHnd9RUbI= >>
    // ----------- >>
    public void buscarPelicula() {
    // ----------- << method.body@AAAAAAF9WbLHnd9RUbI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbMf9d9Y9rc= >>
    // ----------- >>
    public void login() {
    // ----------- << method.body@AAAAAAF9WbMf9d9Y9rc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbOxdd9fmg4= >>
    // ----------- >>
    public void rentar() {
    // ----------- << method.body@AAAAAAF9WbOxdd9fmg4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9WZMKK90MfGA= >>
// ----------- >>
}