/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WZMkHd03v/A= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WZMkHd03v/A= >>
// ----------- >>
public class ManejadorBD {
    // ----------- << attribute.annotations@AAAAAAF9WaXZfd6zA+g= >>
    // ----------- >>
    private String nombreBD;

    // ----------- << attribute.annotations@AAAAAAF9WaZhfd66Tag= >>
    // ----------- >>
    private String contraseña;

    // ----------- << attribute.annotations@AAAAAAF9beL1n1AF8QA= >>
    // ----------- >>
    private String nombreTabla;

    // ----------- << attribute.annotations@AAAAAAF9beTzylHzwYk= >>
    // ----------- >>
    private Sucursal ;

    // ----------- << attribute.annotations@AAAAAAF9beUgCVK5fJQ= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAF9beWVOVPOc5s= >>
    // ----------- >>
    private Transaccion ;

    // ----------- << attribute.annotations@AAAAAAF9bea+FVjbkvI= >>
    // ----------- >>
    private Pelicula ;

    // ----------- << attribute.annotations@AAAAAAF9bebI4FlLiXk= >>
    // ----------- >>
    private Cliente ;

    private String getNombreBD() {
        return nombreBD;
    }

    private String getContraseña() {
        return contraseña;
    }

    private String getNombreTabla() {
        return nombreTabla;
    }

    public Sucursal get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public Transaccion get() {
        return ;
    }

    public Pelicula get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    private void setNombreBD(String nombreBD) {
        this.nombreBD = nombreBD;
    }

    private void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

    private void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Transaccion ) {
        this. = ;
    }

    public void set(Pelicula ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Transaccion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Pelicula _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF9Waa/Nd7DZ+0= >>
    // ----------- >>
    public void conectar() {
    // ----------- << method.body@AAAAAAF9Waa/Nd7DZ+0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9Wabj5d7KO3o= >>
    // ----------- >>
    public void solicitar() {
    // ----------- << method.body@AAAAAAF9Wabj5d7KO3o= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WacfVd7RSCU= >>
    // ----------- >>
    public void modificar() {
    // ----------- << method.body@AAAAAAF9WacfVd7RSCU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9Wac15d7Y0iw= >>
    // ----------- >>
    public void eliminar() {
    // ----------- << method.body@AAAAAAF9Wac15d7Y0iw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WadQL97fAFg= >>
    // ----------- >>
    public void agregar() {
    // ----------- << method.body@AAAAAAF9WadQL97fAFg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9WZMkHd03v/A= >>
// ----------- >>
}