/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WYw6K9zhAfs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WYw6K9zhAfs= >>
// ----------- >>
public class Pelicula {
    // ----------- << attribute.annotations@AAAAAAF9WaFxPN59j6w= >>
    // ----------- >>
    private int idPelicula;

    // ----------- << attribute.annotations@AAAAAAF9WaI57d6LiOk= >>
    // ----------- >>
    private String director;

    // ----------- << attribute.annotations@AAAAAAF9WaJjgt6SA4c= >>
    // ----------- >>
    private boolean estreno;

    // ----------- << attribute.annotations@AAAAAAF9WaK0pd6ZZkU= >>
    // ----------- >>
    private String genero;

    // ----------- << attribute.annotations@AAAAAAF9WaUCwt6g1qs= >>
    // ----------- >>
    private String year;

    // ----------- << attribute.annotations@AAAAAAF9WaVQs96njyg= >>
    // ----------- >>
    private char clasificacion;

    // ----------- << attribute.annotations@AAAAAAF9beR3vlAzCU8= >>
    // ----------- >>
    private Transaccion ;

    // ----------- << attribute.annotations@AAAAAAF9bea+FVjc7kY= >>
    // ----------- >>
    private ManejadorBD ;

    private int getIdPelicula() {
        return idPelicula;
    }

    private String getDirector() {
        return director;
    }

    private boolean isEstreno() {
        return estreno;
    }

    private String getGenero() {
        return genero;
    }

    private String getYear() {
        return year;
    }

    private char getClasificacion() {
        return clasificacion;
    }

    public Transaccion get() {
        return ;
    }

    public ManejadorBD get() {
        return ;
    }

    private void setIdPelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }

    private void setDirector(String director) {
        this.director = director;
    }

    private void setEstreno(boolean estreno) {
        this.estreno = estreno;
    }

    private void setGenero(String genero) {
        this.genero = genero;
    }

    private void setYear(String year) {
        this.year = year;
    }

    private void setClasificacion(char clasificacion) {
        this.clasificacion = clasificacion;
    }

    public void set(Transaccion ) {
        this. = ;
    }

    public void set(ManejadorBD ) {
        this. = ;
    }

    public void link(Transaccion _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(ManejadorBD _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF9WbFKdd8rBUA= >>
    // ----------- >>
    public void mostrar() {
    // ----------- << method.body@AAAAAAF9WbFKdd8rBUA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbGNVt8yTVU= >>
    // ----------- >>
    public void agregar() {
    // ----------- << method.body@AAAAAAF9WbGNVt8yTVU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbGljd85Mog= >>
    // ----------- >>
    public void eliminar() {
    // ----------- << method.body@AAAAAAF9WbGljd85Mog= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbG/zt9A0pY= >>
    // ----------- >>
    public void cambiarEstreno() {
    // ----------- << method.body@AAAAAAF9WbG/zt9A0pY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9WYw6K9zhAfs= >>
// ----------- >>
}