/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WZSm5925c90= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WZSm5925c90= >>
// ----------- >>
public class Sucursal {
    // ----------- << attribute.annotations@AAAAAAF9Waz0nt7yKdM= >>
    // ----------- >>
    private int idSucursal;

    // ----------- << attribute.annotations@AAAAAAF9Wa0ost76gkU= >>
    // ----------- >>
    private String direccion;

    // ----------- << attribute.annotations@AAAAAAF9Wa1ibd8C7es= >>
    // ----------- >>
    private String telefono;

    // ----------- << attribute.annotations@AAAAAAF9Wa20mN8MNPs= >>
    // ----------- >>
    private String horario;

    // ----------- << attribute.annotations@AAAAAAF9beTzylH0z9Q= >>
    // ----------- >>
    private ManejadorBD ;

    private int getIdSucursal() {
        return idSucursal;
    }

    private String getDireccion() {
        return direccion;
    }

    private String getTelefono() {
        return telefono;
    }

    private String getHorario() {
        return horario;
    }

    public ManejadorBD get() {
        return ;
    }

    private void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }

    private void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    private void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    private void setHorario(String horario) {
        this.horario = horario;
    }

    public void set(ManejadorBD ) {
        this. = ;
    }

    public void link(ManejadorBD _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF9WbCUxd8VP7A= >>
    // ----------- >>
    public void agregarSucursal() {
    // ----------- << method.body@AAAAAAF9WbCUxd8VP7A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbDWFt8dti8= >>
    // ----------- >>
    public void consultar() {
    // ----------- << method.body@AAAAAAF9WbDWFt8dti8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9WbEAfd8k4i8= >>
    // ----------- >>
    public void eliminar() {
    // ----------- << method.body@AAAAAAF9WbEAfd8k4i8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9WZSm5925c90= >>
// ----------- >>
}