/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WZPeDN1jmBE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WZPeDN1jmBE= >>
// ----------- >>
public class Transaccion {
    // ----------- << attribute.annotations@AAAAAAF9WbQK3d9mpZY= >>
    // ----------- >>
    private int idTransaccion;

    // ----------- << attribute.annotations@AAAAAAF9WbQt299tFG4= >>
    // ----------- >>
    private String cliente;

    // ----------- << attribute.annotations@AAAAAAF9Wbeu/d92GE0= >>
    // ----------- >>
    private String pelicula;

    // ----------- << attribute.annotations@AAAAAAF9WbfJR999tp0= >>
    // ----------- >>
    private String detalles;

    // ----------- << attribute.annotations@AAAAAAF9beR3vlAypTQ= >>
    // ----------- >>
    private Pelicula ;

    // ----------- << attribute.annotations@AAAAAAF9beSYYlB1lZ4= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAF9beWVOVPPBJU= >>
    // ----------- >>
    private ManejadorBD ;

    private int getIdTransaccion() {
        return idTransaccion;
    }

    private String getCliente() {
        return cliente;
    }

    private String getPelicula() {
        return pelicula;
    }

    private String getDetalles() {
        return detalles;
    }

    public Pelicula get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public ManejadorBD get() {
        return ;
    }

    private void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }

    private void setCliente(String cliente) {
        this.cliente = cliente;
    }

    private void setPelicula(String pelicula) {
        this.pelicula = pelicula;
    }

    private void setDetalles(String detalles) {
        this.detalles = detalles;
    }

    public void set(Pelicula ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(ManejadorBD ) {
        this. = ;
    }

    public void link(Pelicula _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(ManejadorBD _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF9Wb40Vt+FgUo= >>
    // ----------- >>
    public void confirmar() {
    // ----------- << method.body@AAAAAAF9Wb40Vt+FgUo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9Wb5sdd+MHQc= >>
    // ----------- >>
    public void rechazar() {
    // ----------- << method.body@AAAAAAF9Wb5sdd+MHQc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9WZPeDN1jmBE= >>
// ----------- >>
}