/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Clases;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9WZQ8UN2OUtY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9WZQ8UN2OUtY= >>
// ----------- >>
public class Usuario {
    // ----------- << attribute.annotations@AAAAAAF9WZc4/d42XbQ= >>
    // ----------- >>
    private void Attribute1;

    public void getAttribute1() {
        return Attribute1;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

// ----------- << class.extras@AAAAAAF9WZQ8UN2OUtY= >>
// ----------- >>
}